### ISSUE TITLE
Add Kafka ingest

### ISSUE THREAD

**Issue by eranra** [netobserv/flowlogs2metrics#14]

**Comment by eranra** [comment]
Align with https://github.com/netobserv/goflow2-kube-enricher/pull/23

@jotak -  this is the corresponding issue we have in `flowlogs2metrics`

**Comment by jotak** [comment]
note that there's several options on the table about how to use kafka, we'll discuss about that shortly

**Comment by eranra** [comment]
Ok, so moving back to on-hold
