### ISSUE TITLE
Write: Add write to Loki 

### ISSUE THREAD

**Issue by eranra** [netobserv/flowlogs2metrics#63]

**Comment by jotak** [comment]
For information here is the loki config in goflow-kube: https://github.com/netobserv/goflow2-kube-enricher/blob/main/pkg/config/config.go#L32-L51
And the exporter implementation: https://github.com/netobserv/goflow2-kube-enricher/blob/main/pkg/export/loki.go (btw the current "extractTimestamp" function is probably not optimal)

I think among the different config tweaks that we have, some of them could be implemented at another stage. Eg. there is `IgnoreList` which could be implemented during the Transform stage maybe (this is to filter out unwanted fields).

Some settings are not nicely documented so don't hesitate to ask if you have questions
