### ISSUE TITLE
[Bug] Double increment in OperationCount

### ISSUE THREAD

**Issue by ronensc** [netobserv/flowlogs2metrics#81]
When using `OperationCount`, it seems that each entry is counted twice.

First increment for `OperationCount` only:
https://github.com/netobserv/flowlogs2metrics/blob/c1aebd8ac20ab80b05e505361129af1097267ef3/pkg/pipeline/extract/aggregate/aggregate.go#L126

Second increment that happens anyway:
https://github.com/netobserv/flowlogs2metrics/blob/c1aebd8ac20ab80b05e505361129af1097267ef3/pkg/pipeline/extract/aggregate/aggregate.go#L148

I believe the first increment is redundant.

**Comment by eranra** [comment]
@ronensc the first reference  just sets the `value` field ... it doesn't **change** `count` the second reference changes count adding 1 to the value. So I do not think that things are counted twice.

**Comment by ronensc** [comment]
Oops, missed that `value` in the first reference... closing...
